* RASGOS 
  Los rasgos son aquellos atributos que encasillan a tu personaje, diferenciandolo de otro.
  Asimismo, los rasgos pueden ir mejorando con el tiempo, y se dividen en rasgos basicos
  (caracteristicas mas visibles) y rasgos avanzados (yendo desde talentos, habilidades,
  hasta los conocimientos profesionales de tu personaje).

** Tower Points  
   Desde el momento en que se entra a la torre interior, el cuerpo de un regular se va
   acostumbrando a la alta densidad del shinsoo. Por lo tanto, a medida que se suben los 
   pisos de la torre, el regular va recibiendo "Tower Points" que poder usar en sus rasgos.
** Basicos 
*** Fisico 
**** Fuerza
     Es la potencia fisica, determina tu capacidad para levantar o empujar.
     Se emplea para golpear, romper o cargar cosas.
     - Malo          [1]: Puede levantar hasta 30kg. 
     - Comun         [2]: Puede levantar hasta 60kg.
     - Bueno         [3]: Puede levantar hasta 120kg.
     - Excepcional   [4]: Puede levantar hasta 240kg.
     - Sobresaliente [5]: Puede levantar hasta 350kg.
**** Agilidad
     Determina la agilidad general del personaje, incluyendo la velocidad,
     los reflejos y punteria. Es utilizado para manejo de armas ligeras, 
     y armas arrojadizas (a distancia).
     - Malo          [1]: Alcanzas 20km/h.
     - Comun         [2]: Alcanzas 35km/h.
     - Bueno         [3]: Alcanzas 50km/h.
     - Excepcional   [4]: Alcanzas 75km/h.
     - Sobresaliente [5]: Alcanzas 90km/h.
**** Aguante
     Refleja la salud, dureza y vigor del personaje. 
     Es el medidor de cuanto castigo es capaz de soportar antes de
     sufrir un trauma fisico grave.
     - Malo          [1]: No soporta un ataque de viento a presion.
     - Comun         [2]: Saber como resistir golpes.
     - Bueno         [3]: Tienes una alta resistencia a golpes.
     - Excepcional   [4]: Puedes permanecer hasta 6 horas corriendo.
     - Sobresaliente [5]: Tienes una constitucion digna de un ranker, 
                          podrias aguantar hemorragias graves sin 
                          recibir demasiado castigo.
*** Social 
**** Aspecto
     Es una medida del atractivo del personaje, la primera impresion
     que causa. 
     - Malo          [1]: La gente se aparta en tu presencia.
     - Comun         [2]: No resaltas en la multitud, para bien, o para mal.
     - Bueno         [3]: Generas una buena impresion, tiendes a familiarizarte rapido.
     - Excepcional   [4]: La gente te ama y se arremolina a tu alrededor.
     - Sobresaliente [5]: Inolvidable. Eres definitivamente el recuerdo mas preciado
                          en la vida de las masas.
**** Carisma
     Es la capacidad de un personaje para dejar su impresion en los demas.
     Simboliza la lengua de plata, el pico de oro o el semblante amenazador.
     - Malo          [1]: Hay algo un poco asqueroso en ti.
     - Comun         [2]: Sueles caer bien, y tienes algunos amigos.
     - Bueno         [3]: La gente siempre confia en ti.
     - Excepcional   [4]: Posees un gran magnetismo personal.
     - Sobresaliente [5]: Podrias dar discursos de horas y la gente no
                          apartaria su atencion de ti.
**** Negocio
     Simboliza la capacidad de un personaje para manipular y embaucar,
     o confundir a otras personas.
     - Malo          [1]: Una persona de pocas e ineficaces palabras.
     - Comun         [2]: A veces puedes enganar a las personas, como todos.
     - Bueno         [3]: Siempre consigues descuentos. 
     - Excepcional   [4]: Podrias ser politico, o lider de una secta.
     - Sobresaliente [5]: Podrias convencer a alguien para sacrificarse por ti.
*** Mental 
**** Intelecto
     Representa la capacidad de la persona para retener hechos y conocimientos,
     asi como tambien razonar, resolver problemas y evaluar situaciones. 
**** Percepcion
     Es la capacidad del personaje para observar consciente e inconscientemente
     el ambiente que le rodea.
     - Malo          [1]: Te pasas la mayor parte del tiempo absorto.
     - Comun         [2]: Lo sutil se te escapa, pero eres capaz de captar
                          el cuadro general.
     - Bueno         [3]: Percibes ambientes, texturas y cambios minusculos
                          en tu entorno.
     - Excepcional   [4]: Practicamente nada se te escapa.
     - Sobresaliente [5]: Observas inmediatamente cosas casi imperceptibles
                          para los sentidos humanos.
**** Voluntad
** TODO Avanzados 
*** Talentos 
**** Alerta
**** Combate
**** Consciencia
*** Habilidades 
**** Sigilo
**** Latrocinio
**** Supervivencia
*** Conocimientos 
**** Politica
**** Investigacion
**** Shinsoo
